language: python
python:
  - 3.7
  - 3.6
  - 3.5
install:
  - pip install pipenv flake8 python-coveralls safety
  - pipenv install --deploy
script:
  - ./manage.py migrate
  - coverage run manage.py test
  - flake8 .
  - safety check
after_success:
  - coveralls
